---
title: "git_01"
author: "Holden Katin-Bayer"
date: "Fall 2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
The Walrus and the Carpenter by Lewis Caroll  
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night."  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
The Road Not Taken by Robert Frost  
"Two roads diverged in a yellow wood,  
  And sorry I could not travel both  
And be one traveler, long I stood  
  And looked down one as far as I could  
To where it bent in the undergrowth;"

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter or any other poem here!-->
The Jabberwocky by Lewis Caroll  
"Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.'  
      
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines, I'm inserting another poem by Lewis Caroll here!-->
The Hunting of the Snark by Lewis Caroll    
Fit the First  
            The Landing    

"Just the place for a Snark!" the Bellman cried,  
   As he landed his crew with care;  
Supporting each man on the top of the tide  
   By a finger entwined in his hair.  

"Just the place for a Snark! I have said it twice:  
   That alone should encourage the crew.  
Just the place for a Snark! I have said it thrice:  
   What I tell you three times is true."  

The crew was complete: it included a Boots—  
   A maker of Bonnets and Hoods—  
A Barrister, brought to arrange their disputes—  
   And a Broker, to value their goods.  